### ISSUE TITLE
[IMPROVEMENT] debugbar without SilverStripe CMS

### ISSUE THREAD

**Issue by a2nt** [lekoala/silverstripe-debugbar#102]
Not sure why this modules required: silverstripe/siteconfig, silverstripe/admin
But it will be nice to use debugbar without silverstripe CMS installed

**Comment by robbieaverill** [comment]
+1, we should at least make any CMS coupling optional

**Comment by lekoala** [comment]
any idea how to make tests still working while having optional dependencies?

**Comment by robbieaverill** [comment]
We could make the cms a dev dependency or put class exists checks into the tests that need Page etc and skip them if not installed

**Comment by robbieaverill** [comment]
We'll need to replace the implementation of `LeftAndMain::create()->CMSVersion()` to get the SS version in SilverStripeCollector.

There is some information that won't be available to be collected without SiteConfig. See usages of `SilverStripeCollector::getConfigData()` which uses SiteConfig's data.

Our `LeftAndMainExtension` will need a `if (!class_exists(BaseLeftAndMainExtension::class)) { return; }` check above the class declaration (@ScopeyNZ's favourite PHP "feature").

`DebugBar::isAdminUrl()` will need to be adjusted to fall back to using "admin" if the configured admin URL isn't available from the admin module.

YAML config will work without the root classes they reference existing.

@a2nt pull requests for this would be welcomed!

**Comment by lekoala** [comment]
fixed on master
