### ISSUE TITLE
[IMPROVEMENT] Display cached variables

### ISSUE THREAD

**Issue by a2nt** [lekoala/silverstripe-debugbar#104]
It would be awesome to display cached variables: name, value, ttl

```
use SilverStripe\Core\Cache\FilesystemCacheFactory;
...
$cache = new FilesystemCacheFactory('data');
$this->cache = $cache->create('EventsAPI');
$this->cache->set('token', 'test', 3600);
```

**Comment by lekoala** [comment]
so not so easy, but here it goes https://github.com/lekoala/silverstripe-debugbar/commit/d4da04691594a5b3338d031b3a36887caa864b21

it does not take into account the name of the cache

<img width="306" alt="image" src="https://github.com/lekoala/silverstripe-debugbar/assets/250762/ab443af3-ac61-4915-a224-8907ec4ec33f">

if i'm not wrong, the EventsAPI parameter is never read

https://github.com/silverstripe/silverstripe-framework/blob/158d51a0a5b4201db068ab7f9fdeabe51e041366/src/Core/Cache/FilesystemCacheFactory.php#L27-L35

**Comment by lekoala** [comment]
closing this since it seems done :)
