### ISSUE TITLE
Javascript bindToJquery Error in debugbar.js Line 1115

### ISSUE THREAD

**Issue by tzeller** [lekoala/silverstripe-debugbar#106]
Silverstripe: 4.1.2
Php: 7.1.12
Jquery: 3.3.1
Silverstripe-debugbar: 2.x-dev and others

i get a javascript error on the front end - not in the cms and can't figure out why:

Line: 1115: undefined is not a function (near '...jq(document).ajaxComplete...')

**Comment by tzeller** [comment]
figure it out and changed in debugbar.js line 1115:
- jq(document).ajaxComplete(function(e, xhr, settings) {
+ $(document).ajaxComplete(function(e, xhr, settings) {

**Comment by robbieaverill** [comment]
Thanks @tzeller, would you like to make a pull request?

**Comment by robbieaverill** [comment]
Hi @tzeller, the code you're referring to is party of the underlying [php-debugbar library](https://github.com/maximebf/php-debugbar/), if you're still experiencing this problem I'd recommend bring up the issue on that repository
