### ISSUE TITLE
Destroying the session causes an error

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#108]
When logging out, or just manually destroying the session, the SilverStripeCollector attempts to loop over a `null` result of getting the session, causing a Warning to be thrown.

![screenshot_2018-10-24 get](https://user-images.githubusercontent.com/680570/47398986-24101c00-d793-11e8-96b7-67c02f3bb7a3.png)

**Comment by robbieaverill** [comment]
Seems like a little bit of casting could maybe fix this. Fancy a pull request? 🙂

**Comment by Firesphere** [comment]
I just _knew_ you'd say that 😆

**Comment by robbieaverill** [comment]
I can't reproduce this on version 2.0.0, but that doesn't matter because @pine3ree already fixed this in #107.

I'll tag 2.0.1 now with the patch in it.
