### ISSUE TITLE
PHP 7.2 upgrade

### ISSUE THREAD

**Issue by adrian-stein** [lekoala/silverstripe-debugbar#111]
Is there any plans to make this compatible with 7.2. I notice there is a Object extends in DebugBar.php. Would this be the only amend to get it working with 7.2??

**Comment by robbieaverill** [comment]
Hey @adrian-stein, we'd welcome a pull request to implement compatibility with PHP 7.2. You can have a look at most of the commercially supported SilverStripe modules (blog, userforms, etc) for examples of how to do this - e.g. [this commit](https://github.com/silverstripe/silverstripe-userforms/commit/d327f0d53f229998300daf825e6399bfe790bb2b).

**Comment by sminnee** [comment]
PR in #112

**Comment by robbieaverill** [comment]
Done in #112 and tagged as 1.2.0-beta1
