### ISSUE TITLE
config_collector disables FulltextSearchable

### ISSUE THREAD

**Issue by jmfederico** [lekoala/silverstripe-debugbar#115]
# Versions
`silverstripe/cms` => 4.3.3
`lekoala/silverstripe-debugbar` => 2.0.3

# Problem
Enabling `config_collector` disabled the Search extension.

# Information
I just installed `silverstripe-debugbar` on a SilverStripe installation based on `silverstripe/recipe-cms` 4.3 with `FulltextSearchable::enable()`, and noticed that my `$SearchForm` was not being printed.

I have not dug much into it, but seems like `config_collector` modifies the configurations disabling the search extension.
After disabling `config_collector`, the Search functionality came back.

The results from `d(ContentController::get_extensions())` where different after enabling `config_collector`

**Comment by lekoala** [comment]
any idea what might cause this? isn't it because the FulltextSearchable::enable() is called after the collector is initialised? maybe we prevent any further change when creating the collector

**Comment by lekoala** [comment]
i updated the readme to warn users about this. it may have been fixed meanwhile with the recents changes on the config proxy. so i'll close for now since the issue is documented and potentially fixed.
