### ISSUE TITLE
Odd behaviour when using the Injector in SS 4.4.0

### ISSUE THREAD

**Issue by elliot-sawyer** [lekoala/silverstripe-debugbar#117]
I recently performed an upgrade to SilverStripe 4.4 in a project that used multiple authenticators. One of the features of our project is to use an OAuth provider for normal use, but allow the default email/password authenticator for some users with a cookie set (typically support staff). This requires using the Injector to remove all authenticators first, then adding the oauth provider, then the default one if it is set.

For reasons that are still unclear to our team, [removing the debugbar module fixes the problem](https://slackarchive.silverstripe.org/slack-archive/message/314312#msg_314312). Cheers to thats4shaw on Slack for pointing me in this direction. He suggested Debugbar is doing something "strange" with the Injector, but wasn't sure what it was. He also suggested it was "[blanking all the config overrides](https://slackarchive.silverstripe.org/slack-archive/search/?Query=debugbar&Channel%5B%5D=10&User%5B%5D=89&action_doSearch=Search)"

[The code sample is here](https://slackarchive.silverstripe.org/slack-archive/message/314303#msg_314303)

**Comment by robbieaverill** [comment]
Interesting. Yes, this module does add a proxy class to monitor config calls. It was introduced in https://github.com/lekoala/silverstripe-debugbar/pull/60. It's highly likely that your project code config is running after the debugbar code initialises this proxy. Should be easy enough to reproduce with your code example (thanks)

**Comment by elliot-sawyer** [comment]
The example is almost exactly the same one from the LDAP Authenticator docs, if you need something public to test with: https://github.com/silverstripe/silverstripe-ldap/blob/1/docs/en/developer.md#bypass-auto-login

We use this OAuth configuration to reset the authenticators: https://github.com/bigfork/silverstripe-oauth-login#replacing-the-default-authenticator

**Comment by lekoala** [comment]
@elliot-sawyer Potentially fixed with this https://github.com/lekoala/silverstripe-debugbar/commit/bb6c676296e86d018f6100f308c5e1343fb35ec6 if you had the same issue as me :) somehow calls to config did not store value dynamic values anymore. Proxying everything properly seems to remove the issue on my end

**Comment by lekoala** [comment]
closing for now feel free to reopen if the issue happens again
