### ISSUE TITLE
ClickToShowFields appended to & duplicating queries

### ISSUE THREAD

**Issue by Acen** [lekoala/silverstripe-debugbar#119]
Hey there - looking through our db queries and it seems like the extension is appended a duplicate query against the db records.

Specifically:
https://github.com/lekoala/silverstripe-debugbar/blame/37e79e43d29fa32f98790d2bf60a89ca89e81055/code/Extension/ProxyDBExtension.php#L111

Just looking to have an idea as to why.

**Comment by Acen** [comment]
I noticed later in the day, that it's allowing you to click on the result, with this query, and it shows the variable names (aka fields) used in the query.

I wonder if it'll be plausible to move the logic over to like, the actual query.

**Comment by bergice** [comment]
It's there to keep the query readable. The comment at the top of the section explains it: `// Sometimes, the select statement can be very long and unreadable`.

> I wonder if it'll be plausible to move the logic over to like, the actual query.

@Acen why would you want this?

**Comment by Acen** [comment]
@bergice Primarily, the ability to see the fields that are being queried seems like it should just be supported by default. If a select statement is long or not shouldn't be on the onerous understanding on the user* as to why the interaction is going to be different.

Plus when debugging queries, having a duplication of practically every call just confuses rather than helps, regardless of what function was trying to be provided. Which is what I was looking through code in the first place for - why was this happening?

So, seems like a solution of "pushing this random click to get more data" logic into the display of the actual query (making it so every query is just clickable and getting the same thing this pseudo query returns) makes sense.

🤷 

*English is my first language and I couldn't work out how to use "onerous" correctly. yolo

**Comment by lekoala** [comment]
@Acen I guess you are right it's more the responsability on the display side. this is more of a workaround the debugbar widgets themselves, it was much easier at the time to do that rather than adjusting the debugbar widget itself. So really it's a matter of using 3 lines of php or having to test and develop functionnalities that don't exist on the frontend. :-)

**Comment by GuySartorelli** [comment]
Sounds like this issue was just to ask a question which has now been answered, so I'm going to close it.
If there is actually a problem here, or a request for some enhancement, feel free to re-open the issue with more details.
