### ISSUE TITLE
Instructions on how to add a tab to the debugbar

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#124]
For my CSP headers module, I would like to add a debugbar, to make it easier for devs to inspect and debug the headers generated (and for my own development reasons, of course)

**Comment by lekoala** [comment]
That would be a great addition.

Basically we need to add an extension point in DebugBar.php after all the addCollector calls. Then in your extension you could add your own collectors, like this:

http://phpdebugbar.com/docs/base-collectors.html

As long as you stick with base collectors it's going to be easy

**Comment by Firesphere** [comment]
Given the methods in DebugBar.php are mostly static, it's going to add some complexity. As extend methods shouldn't be added statically, but dynamically.

**Comment by Firesphere** [comment]
Okay, I got my test tab working. I'll make a PR once I'm happy with the implementation I got so far, and got some tests for it.

**Comment by Firesphere** [comment]
I ran in to a little bit of trouble...
Each value is displayed as "undefined". Or, it's a flattened array with `[Object, Object]`

Care to give me a pointer as to what I'm doing wrong? I'm trying to use the Config widget

**Comment by lekoala** [comment]
Yes the config tab displays key values pairs.you might need to flatten
things out in JSON for example. Not ideal but it does the job.

**Comment by lekoala** [comment]
I think you are right about the extension points. Maybe it's better to simply provide a static callback in DebugBar.php without relying on extension mechanism. A simple "setCustomCollector(callable $callable)" should do the trick

**Comment by Firesphere** [comment]
Good call. I'll play around a bit more :) I'm at a better spot than I was anyway, so, I'll see where I get with the amount of time I have :)

**Comment by Firesphere** [comment]
My original question still stands, but I figured, a Header Collector, would actually be very useful in general, so I'll make a PR for the Header Collector soon. Here's the expanded view. I don't have tests yet, but I'll get to that soon :)
![image](https://user-images.githubusercontent.com/680570/103432238-cfa13a80-4c40-11eb-8bd0-bfd19488bc1d.png)

**Comment by Firesphere** [comment]
Better shot, I hope:
![image](https://user-images.githubusercontent.com/680570/103432247-02e3c980-4c41-11eb-94fc-0124910a5507.png)

p.s.
Happy new year mate!

**Comment by GuySartorelli** [comment]
Looks like #126 adds the requested functionality. Closing this issue.
