### ISSUE TITLE
Compatibility with Silverstripe 4.7 / Symfony-YAML 4

### ISSUE THREAD

**Issue by sb-relaxt-at** [lekoala/silverstripe-debugbar#125]
The symfony yaml component requires "%$Something" to be wrapped in quotes. See https://docs.silverstripe.org/en/4/changelogs/4.7.0/#support-for-symfony-4-components

**Comment by Firesphere** [comment]
This seems to be fixed by now?

**Comment by lekoala** [comment]
yes i think it is, closing the issue
