### ISSUE TITLE
Downstream merge

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#129]
Is it possible to add the changes to the SS3 branch?

**Comment by lekoala** [comment]
Most of them could be easily added yes. But I basically only work on stuff I'm actually using and I have no active ss3 projects that require the new changes. If someone wants to make a pull requests I would happily accept them.

**Comment by Firesphere** [comment]
I'll have a look then, since I have an SS3 project going at the moment :)

**Comment by GuySartorelli** [comment]
Closing this issue as it pertains to old versions that are no longer supported.
