### ISSUE TITLE
Possibility to highlight duplicated sql queries

### ISSUE THREAD

**Issue by wernerkrauss** [lekoala/silverstripe-debugbar#13]
Is there a possibility to highlight the sql queries?

I just saw: 

```
71 statements were executed, 12 of which were duplicated
```

but i don't know how to _easily_ find those 12...

**Comment by lekoala** [comment]
you have a filter "only duplicated queries" that you can click on at the bottom of the list. each duplicated query as it's own number in a little badge to help you.
Then, you have to rely on the source trace to help you identify where they come from.

**Comment by wernerkrauss** [comment]
Oh, that button is quite invisible. Thanks for the info....

Sorting that list by time or duplicated queries (so i see that query is called there and there) would be a really great feature

**Comment by lekoala** [comment]
I added filters for each duplicate, this way you can display only one specific duplicated query at a time in the list.

Sorting is not really feasible without deep changes on how the list is rendered.
