### ISSUE TITLE
Undefined Index notices (and are you taking PR's for the 3.x branches?)

### ISSUE THREAD

**Issue by muppsy007** [lekoala/silverstripe-debugbar#131]
Branch: 1.2

Pretty easy one. Getting undefined index notices out of DebugBarLogWriter as only some array elements are being checked before use.

```
[NOTICE] UNDEFINED INDEX: FUNCTION
GET /my/page
Line 61 in /vagrant/site/debugbar/code/DebugBarLogWriter.php
```     

[Offending code block.](https://github.com/lekoala/silverstripe-debugbar/blob/d6cc16e20fd10ef418fbabb345c46831569a4406/code/DebugBarLogWriter.php#L56)

I'm not sure if there's some downstream issue/cause with these elements having not been set, but it looks like checking them for existence was already in mind due to the line number element being checked first.

Will a PR to the 1.x branch be merged if I do one? This module is so helpful, but I'd rather not turn notices off on Dev just for it. My current thinking is to simple do an isset check on the string elements and default to '' unless there's a better idea.

**Comment by lekoala** [comment]
@muppsy007 yes that seem easy enough to fix with a simple if. You are welcome to make a PR i'll happily merge anything that works :-)

**Comment by muppsy007** [comment]
Thanks @lekoala. I'll have a look on the the weekend.

Since posting I worked our that this code actually ends up piping log messages and code locations into the Messages tab of the debugbar. The likely reason why mine are empty is because we're using a custom log writer that doesn't have the fields it's looking for (which I will sort in our code, because that's a handy feature). So having blank defaults will just result in a message "::0" in the toolbar. Which is of no use to anyone. 

Perhaps a better option is to check if a bare minimum is present in the array and if not, skip adding the line altogether? Or maybe a default message about a log being triggered but in a non standard format? 

What do you think?

**Comment by lekoala** [comment]
@muppsy007 yes, I guess your logger probably follows psr-3? if so, supporting that interface would make sense. i don't mind if we add a couple if isset checks to see what is available in the $event variable and log accordingly

**Comment by GuySartorelli** [comment]
Closing this issue as it pertains to old versions that are no longer supported.
