### ISSUE TITLE
php 8.1 Deprecation

### ISSUE THREAD

**Issue by OldStarchy** [lekoala/silverstripe-debugbar#136]
[Deprecated] trim(): Passing null to parameter #1 ($string) of type string is deprecated

Line 19 in /app/vendor/lekoala/silverstripe-debugbar/code/Aspects/CacheAfterCallAspect.php

https://github.com/lekoala/silverstripe-debugbar/blob/a9e5bddd155e4e8acb6b3af12db7a154aa4e3fb6/code/Aspects/CacheAfterCallAspect.php#L19

Put this in your `.env` to see this warning

```dotenv
SS_DEPRECATION_ENABLED=true
```

**Comment by lekoala** [comment]
should be fixed in https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.1.0
