### ISSUE TITLE
upgrading to cms 4.11 dependency issue

### ISSUE THREAD

**Issue by vinstah** [lekoala/silverstripe-debugbar#137]
using version ^2 I get Uncaught Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 37 (near "DebugBarMiddleware: %$DebugBarMiddleware")

so I used dev-master for this module and then composer said it requires "tractorcow/silverstripe-proxy-db": "^0.1.0" but my currently installed from composer is "tractorcow/silverstripe-proxy-db": "1.0"

**Comment by rafaeldsousa** [comment]
Yep, the composer file requirements needs updating to get the module not to conflict with latest recipe requirements.

```
 Root composer.json requires silverstripe/recipe-ccl ~2.11.0@stable -> satisfiable by silverstripe/recipe-ccl[2.11.0].
    - You can only install one version of a package, so only one of these can be installed: tractorcow/silverstripe-proxy-db[0.1.0, 1.0.0].
    - silverstripe/auditor[2.5.0, ..., 2.x-dev] require tractorcow/silverstripe-proxy-db ^1 -> satisfiable by tractorcow/silverstripe-proxy-db[1.0.0].
    - lekoala/silverstripe-debugbar 2.0.8 requires tractorcow/silverstripe-proxy-db ^0.1.0 -> satisfiable by tractorcow/silverstripe-proxy-db[0.1.0].
    - silverstripe/recipe-ccl 2.11.0 requires silverstripe/auditor ~2.5.0@stable -> satisfiable by silverstripe/auditor[2.5.0, 2.5.x-dev].
    - Root composer.json requires lekoala/silverstripe-debugbar 2.0.8 -> satisfiable by lekoala/silverstripe-debugbar[2.0.8].
```

**Comment by GuySartorelli** [comment]
Looks like this is addressed by https://github.com/lekoala/silverstripe-debugbar/pull/138 which just needs to be tagged.

**Comment by lekoala** [comment]
yes indeed, i just tagged https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.1.0

**Comment by GuySartorelli** [comment]
Awesome. I'll close this as fixed then.
