### ISSUE TITLE
Strict Notice with SS3.5.0

### ISSUE THREAD

**Issue by wernerkrauss** [lekoala/silverstripe-debugbar#14]
I got this after updating from SS 3.4.1 to 3.5:

> [Strict Notice] Declaration of DebugBarDatabaseNewProxy::benchmarkQuery() should be compatible with SS_Database::benchmarkQuery($sql, $callback, $parameters = Array)

**Comment by wernerkrauss** [comment]
Got some more today while running BetterI18NTextCollectorTask (which includes all files somehow)

> [Strict Notice] Declaration of DebugBarDatabaseProxy::benchmarkQuery() should be compatible with SS_Database::benchmarkQuery($sql, $callback, $parameters = Array)
> Line 0 in /vagrant/www/debugbar/code/DebugBarDatabaseProxy.php

> Fatal error: Declaration of DebugBarDatabaseProxy::comparisonClause() must be compatible with SS_Database::comparisonClause($field, $value, $exact = false, $negate = false, $caseSensitive = NULL, $parameterised = false) in /vagrant/www/debugbar/code/DebugBarDatabaseProxy.php on line 0

> Fatal error: Declaration of DebugBarDatabaseProxy::transactionEnd() must be compatible with SS_Database::transactionEnd($chain = false) in /vagrant/www/debugbar/code/DebugBarDatabaseProxy.php on line 0

> Fatal error: Access level to DebugBarDatabaseProxy::fieldList() must be public (as in class SS_Database) in /vagrant/www/debugbar/code/DebugBarDatabaseProxy.php on line 0

I can provide a PR for this.

**Comment by lekoala** [comment]
merged. strange that I didn't notice any of that before, I used it on a few SS 3.5 websites

**Comment by wernerkrauss** [comment]
Maybe this class isn't used under normal circumstances? That BetterI18NTask reveils many errors I normally don't recognise.
