### ISSUE TITLE
Deprecation warning PHP8.1

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#140]
Similar to #136 , in `DebugBarMiddleware::afterRequest()` on line 106 (and probably later?)
`if (strpos($body, '</body>') !== false) {`
Throws a deprecation error visible on screen before a redirect is executed.

**Comment by RuthAdele** [comment]
I just came here to report the same issue!

Here's some more detail:

**Error**
`[Deprecated] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated`

**Trace**
```
strpos(, </body>)
DebugBarMiddleware.php:106
```
```
104         // Inject init script into the HTML response
105         $body = $response->getBody();
106         if (strpos($body, '</body>') !== false) {
```

**Comment by lekoala** [comment]
fixed in https://github.com/lekoala/silverstripe-debugbar/commit/9b12bab51c8db3447fc513badf9af2cec42e6592
getBody should always return a string, but i guess casting to a string never hurts :)

**Comment by thats4shaw** [comment]
@lekoala could you pretty please tag a new version that includes this.

**Comment by lekoala** [comment]
@thats4shaw tagged in https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.2.0 with the improved CI build
