### ISSUE TITLE
[Idea] Export tab to CSV/Something

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#145]
Sometimes the tab (especially queries!) can get large and wieldy, and a page is only "valid" for so long in certain circumstances (e.g. a webshop order confirmation page)

It would be quite useful to be able to export it to a CSV or something, to save for later analysis.

**Comment by lekoala** [comment]
added in https://github.com/lekoala/silverstripe-debugbar/commit/b17b0542fa1df5b2c36aa0118c192e9b3e2e3d73
