### ISSUE TITLE
Debugbar requirements not included in 4.12

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#146]
As of SilverStripe 4.12, the requirements are not always included. Causing a javascript reference error.

**Comment by lekoala** [comment]
@Firesphere that's odd! any idea what could have changed? is this due to the jquery upgrade?

**Comment by Firesphere** [comment]
I withdraw my issue.

It seems more related to a vendor requirement that stops any other middleware, or undo any other middleware requirements...

Which is a tad dumb, but I'll figure it out :)
