### ISSUE TITLE
CMS 5 - Email tab won't work

### ISSUE THREAD

**Issue by emteknetnz** [lekoala/silverstripe-debugbar#147]
The CMS 5 version in the `3` branch includes code that [references SwiftMailer](https://github.com/lekoala/silverstripe-debugbar/blob/3/code/DebugBar.php#L212)

This won't work in CMS 5 as it now uses symfony/mailer for Email, rather that SwiftMailer

**Comment by lekoala** [comment]
Support added in https://github.com/lekoala/silverstripe-debugbar/commit/51748e9e328abf1c019e440c26c19850e0f383ea

**Comment by lekoala** [comment]
closing this :)
