### ISSUE TITLE
Query trace shows incorrect class/method names

### ISSUE THREAD

**Issue by GuySartorelli** [lekoala/silverstripe-debugbar#152]
The `debug_backtrace()` function shows the class and function that are being _called_ on that line, not the class and method that line live in.
`PRoxyDBExtension::findSource()` doesn't take this into account, so the debugbar ends up giving a class and method which don't line up with the line that it reports.

Note that the `d()` function in `_config.php` does correctly account for that already.

## PRs
- https://github.com/lekoala/silverstripe-debugbar/pull/153

**Comment by GuySartorelli** [comment]
PR was merged

**Comment by lekoala** [comment]
@GuySartorelli thanks :-)
