### ISSUE TITLE
Javascript script is wrongly rendered inside of another javascript file causing tinyMCE to crash and halt loading of CMS

### ISSUE THREAD

**Issue by SvenWesterlaken** [lekoala/silverstripe-debugbar#154]
This error is the same as #142 . After 1 and a half years the bug still exists for me and a colleague and I finally managed to trace it down to the actual culprit:

![image](https://github.com/lekoala/silverstripe-debugbar/assets/16725310/10607295-a29d-45ac-9e10-93980327eea9)

Above is a part of the minified code of TinyMCE generated at runtime (it gets outputted inside `/public/assets/_tinymce/`). At first, I thought this script had a faulty syntax. However, there is nothing wrong with it, we later found out. 

Instead, the problem arises from the `DebugBarMiddleware`: whenever a request is made, the `afterRequest()` tries to inject the script for debugbar to work, which makes sense. Unfortunately, because there is a `</body>` tag inside this javascript file of tinyMCE, the middleware thinks it needs to put the script where my cursor is on the screenshot, causing the TinyMCE script to throw syntax errors.

My guess for an easy fix is to check if the response has an HTML response type (and only then execute the injection) [on line 106 of `MiddleWare/DebugBarMiddleware`](https://github.com/lekoala/silverstripe-debugbar/blob/2.2.1/code/Middleware/DebugBarMiddleware.php#L108) (it might be different by now as we are using version 2.2.1):
```php
if (strpos($body, '</body>') !== false) {
```

It seems to be an uncommon problem to occur, but I guess it can happen on other occasions as well which would affect all versions. Hence why I am creating this new issue.

Some environment info:

Debugbar version: 2.1.0
Silverstripe 4.10.0
PHP 7.4.21

**Comment by lekoala** [comment]
i see. probably the best way then would be to have some kind of placeholder that can be replaced instead of blindly replacing </body> values. that should solve your issue no?

**Comment by SvenWesterlaken** [comment]
That would be even better I think, yes. @lekoala

**Comment by lekoala** [comment]
I added a couple of things here
https://github.com/lekoala/silverstripe-debugbar/commit/cf823499ec13eb7e47054dd266f294f4e55ccac1

you can use the placeholder
it will now also properly detect the first occurence of head or last occurence of body, this way even if there is a string somewhere, it should be safe even without the placeholder

**Comment by SvenWesterlaken** [comment]
I will check later today or this week if that fixes the issue, thanks for the quick response/resolve @lekoala!

**Comment by SvenWesterlaken** [comment]
Unfortunately, I think this won't be sufficient as the TinyMCE code (the js file where the problem occurs) does not need any debugbar attachment whatsoever. Furthermore, I don't have direct control over the content of that file so adding a placeholder would not be possible without a hack. Because, as far as I can see, the code would still execute on the js file to inject the script part. Maybe a bit more context:

In the HTMLEditorField the TinyMCE script is used. This is used at the bottom of the page as a simple import:
```html
<script type="application/javascript" src="/assets/_tinymce/tinymce-cms-af96879d45.js"></script>
```
Part of the content of this js file is shown in the screenshot shared in the first comment. What happens is that the GET request for the content of this file gets intercepted by the middleware and injects (while it shouldn't) the debugbar script inside of the content of the JS file which causes it to have syntax errors.

**Comment by lekoala** [comment]
ooohh i see. Yes indeed the middleware should not try to do anything on assets, it's really odd it gets executed by this. I guess it's because the file is protected and routed through a php controller that runs the whole framework. I'll have a look!

**Comment by SvenWesterlaken** [comment]
Yes. What makes the bug even weirder is that 2 other people on the same Silverstripe project don't have this issue. However, they installed the project sometime later which made us think it had something to do with minor version differences in packages. Besides, this is the only project where I have this bug. So our first guess was to clear the cache & replace lock files for both composer & node, but that didn't work. I would guess that there's a cached/locked version of the TinyMCE file content somewhere. 

Anyway, I do think the content also being replaced in assets could cause problems in other situations. That's why I made the issue instead of making a local fix.

If it helps I can upload a gist of the file content?

**Comment by lekoala** [comment]
@SvenWesterlaken in order to help, you could tell me if the generated file located in /assets/_tinymce/tinymce-cms-xxx.js contains the debugbar code or is it added upon request. Then:
- if it's in the file, try to delete that file, it should call the TinyMCECombinedGenerator. From what i can see, this should not trigger any middleware 
- if it's added when requesting the file, make a request to /assets/_tinymce/tinymce-cms-xxx.js . could you confirm it goes through your public/index.php main entry (add a die in there, it should appear when requesting the file)

**Comment by SvenWesterlaken** [comment]
> * if it's in the file, try to delete that file, it should call the TinyMCECombinedGenerator. From what i can see, this should not trigger any middleware

I already narrowed it down to it being due to the request. The file does not contain the debug code. Also, I added a die with echo inside the TinyMCECombinedGenerator and the debug bar js code does not appear after deleting the TinyMCE file upon generation within the generator. Only when I look up the file in resources in Chrome developer tools. 

> * if it's added when requesting the file, make a request to /assets/_tinymce/tinymce-cms-xxx.js . could you confirm it goes through your public/index.php main entry (add a die in there, it should appear when requesting the file)

I will come back to you with the results on this.

**Comment by SvenWesterlaken** [comment]
Yes @lekoala, I can confirm that a die gets triggered inside of the `public/index.php` when I call a GET request on `/assets/_tinymce/tinymce-cms-af96879d45.js`.

**Comment by lekoala** [comment]
> Yes @lekoala, I can confirm that a die gets triggered inside of the `public/index.php` when I call a GET request on `/assets/_tinymce/tinymce-cms-af96879d45.js`.

ok, so that makes sense (kind of...). This should not happen, so there is almost certainly something wrong with your setup.
It's almost certain that this is due to the htaccess file here public\assets\.htaccess that does this

    # Non existant files passed to requesthandler
    RewriteCond %{REQUEST_URI} ^(.*)$
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule .* ../index.php [QSA]

if you remove these lines, does it still happen?

do you have any idea why a static asset request is routed through your index.php file if the file exists on the filesystem ?

Or maybe there is another htaccess file somewhere (in your root, or parent folder, depending on how your server is configured) with a global rule to rewrite everything to index.php ?

**Comment by SvenWesterlaken** [comment]
Interesting. Commenting out the part in the `/public/assets/.htaccess` did not have an effect. However, commenting out:
```htaccess
# Process through SilverStripe if no file with the requested name exists.
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule .* index.php
```
Inside of the `.htaccess` public folder does have the desired effect.

Am I correct in stating that the problem is within the `.htaccess` file where it should direct the request of static assets directly to the source instead of going over the `index.php`? Which would suggest a line with a rewrite rule for assets is missing?

Maybe there's something you can spot easily that's off?

*/public/.htaccess*:
```
# Deny access to templates (but allow from localhost)
<Files *.ss>
    Require ip 127.0.0.1
</Files>

# Deny access to IIS configuration
<Files web.config>
    Require all denied
</Files>

# Deny access to YAML configuration files which might include sensitive information
<Files ~ "\.ya?ml$">
    Require all denied
</Files>

# Route errors to static pages automatically generated by SilverStripe
ErrorDocument 404 /assets/error-404.html
ErrorDocument 500 /assets/error-500.html

<IfModule mod_rewrite.c>

    # Turn off index.php handling requests to the homepage fixes issue in apache >=2.4
    <IfModule mod_dir.c>
        DirectoryIndex disabled
        DirectorySlash On
    </IfModule>

    SetEnv HTTP_MOD_REWRITE On
    RewriteEngine On

    # Enable HTTP Basic authentication workaround for PHP running in CGI mode
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Deny access to potentially sensitive files and folders
    RewriteRule ^vendor(/|$) - [F,L,NC]
    RewriteRule ^\.env - [F,L,NC]
    RewriteRule silverstripe-cache(/|$) - [F,L,NC]
    RewriteRule composer\.(json|lock) - [F,L,NC]
    RewriteRule (error|silverstripe|debug)\.log - [F,L,NC]

    # Process through SilverStripe if no file with the requested name exists.
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule .* index.php
</IfModule>
```

---

*/public/assets/.htaccess*:
```
#
# Whitelist appropriate assets files.
# This file is automatically generated via File.allowed_extensions configuration
# See AssetAdapter::renderTemplate() for reference.
#

# We disable PHP via several methods
# Replace the handler with the default plaintext handler
AddHandler default-handler php phtml php3 php4 php5 inc

<IfModule mod_php5.c>
    # Turn the PHP engine off
    php_flag engine off
</IfModule>

<IfModule mod_rewrite.c>
    <IfModule mod_env.c>
        SetEnv HTTP_MOD_REWRITE On
    </IfModule>

    RewriteEngine On

    # Allow error pages
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule error[^\\/]*\.html$ - [L]

    # Allow specific file extensions
    RewriteCond %{REQUEST_URI} !^[^.]*[^\/]*\.(?i:css|js|ace|arc|arj|asf|au|avi|bmp|bz2|cab|cda|csv|dmg|doc|docx|dotx|flv|gif|gz|hqx|ico|jpeg|jpg|kml|m4a|m4v|mid|midi|mkv|mov|mp3|mp4|mpa|mpeg|mpg|ogg|ogv|pages|pcx|pdf|png|pps|ppt|pptx|potx|ra|ram|rm|rtf|sit|sitx|tar|tgz|tif|tiff|txt|wav|webm|webp|wma|wmv|xls|xlsx|xltx|zip|zipx|graphql)$
    RewriteRule .* - [F]

    # Non existant files passed to requesthandler
    RewriteCond %{REQUEST_URI} ^(.*)$
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule .* ../index.php [QSA]
</IfModule>
```

**Comment by lekoala** [comment]
EDIT : this is what I have, but it seems it's from an older version. Yours seems good from a fresh install. But at any rate this is what I have

    # Process through SilverStripe if no file with the requested name exists.
    # Pass through the original path as a query parameter, and retain the existing parameters.
    # Try finding framework in the vendor folder first
    RewriteCond %{REQUEST_URI} ^(.*)$
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule .* index.php

note the REQUEST_URI part that is missing
not exactly sure if that should change anything but who knows...

it seems that     RewriteCond %{REQUEST_FILENAME} !-f is triggered for invalid reasons anyway. The doc specify that the file must be a valid regular file (whatever that means). Is your asset folder somehow symlinked, created by a different user, doesn't have the same permissions? 
if you are working on mac or linux, maybe try a good old chmod -r 777 on the whole _tinymce folder and see if that makes any difference

**Comment by SvenWesterlaken** [comment]
Unfortunately, both didn't give any result @lekoala.

We are both using MAMP Pro (me and my colleague who has the problem), maybe we need to adjust some settings in our virtual hosts that cause an error on finding the file and trigger the `RewriteCond %{REQUEST_FILENAME} !-f`. This would justify why it's working for other people on the same project (although they also use MAMP Pro).

**Comment by lekoala** [comment]
@SvenWesterlaken did a quick test by forcing the rewrite on my local project

this fixes it: https://github.com/lekoala/silverstripe-debugbar/commit/4e82107a0084b1d7e182cacf89d34aeb285469ad

probably you might have other issues if your assets are being processed by your controller

also, make sure to get the latest version because from what i see, it should not be included because the assets controller is not an instance of ContentController and therefore, the debugbar should not be generated

see

https://github.com/lekoala/silverstripe-debugbar/blob/4e82107a0084b1d7e182cacf89d34aeb285469ad/code/Extension/ControllerExtension.php#L40-L42

**Comment by SvenWesterlaken** [comment]
Will do some research on the problem with the assets next week. Might put the solution here for anyone else that encounters the same problem and somehow ends up on this issue.

> This fixes it: https://github.com/lekoala/silverstripe-debugbar/commit/4e82107a0084b1d7e182cacf89d34aeb285469ad

This will be released in a patch update, or should I update the resource with a GitHub repo link instead of the package? Also, note that we are still running SS4 so don't know if there are problems with a major version upgrade.

**Comment by lekoala** [comment]
oh that's why you were getting the debugbar

i've tagged
for ss4 https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.2.3
for ss5 https://github.com/lekoala/silverstripe-debugbar/releases/tag/3.0.4

**Comment by SvenWesterlaken** [comment]
> for ss4 https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.2.3

After upgrading works like a charm @lekoala! Thanks for taking the time to look into this. It's funny how it ended up being something completely different than originally thought. 

If you want you can close this issue. I should still be able to comment afterwards if I find out why my assets are triggering the rewrite rule in the `.htaccess`
