### ISSUE TITLE
Cant seem to get working on Website Fontend

### ISSUE THREAD

**Issue by camexapps** [lekoala/silverstripe-debugbar#16]
Hi There,

Just seem to be having an issue getting this working on the front end of the website (admin shows find). I am including my own jQuery, the required CSS/JS from debug bar is loaded, and when I try to debug the DebugBar using in my  Page  Controller init() function:

```
$foo = DebugBar::WhyDisabled();
d($foo);
```

The returned result is 'I don't know why'

There are no errors that I can see being logged (both JS/PHP)

If I can supply you with any useful info I can..

Using SilverStripe 3.5

**Comment by lekoala** [comment]
if it says "i don't know why' it means it's probably enabled (so everything on the php side is fine) but it's not showing for some other reasons : styles could prevent the bar to be displayed, js errors, wrong jquery version, jquery included after debugbar init scripts...

reasons may vary! 
is there any output in your console tab in your browser's developer tools?

**Comment by lekoala** [comment]
do you include jquery on Page::init or in your templates? it should be included in Page::init to make sure it's loaded before debugbar

**Comment by camexapps** [comment]
Thanks for the reply.  Yeah,  no console log errors,  and tried both jquery
1 and 2 libs and its loaded in the head element hard-coded as opposed to
being 'required' .  Just a bit perplexed at the moment. Didn't think ofa
cos style hiding it.  Do u know the name/id of the debug bar element? I
will try digging deeper in the interim

Cheers

**Comment by lekoala** [comment]
very strange!

by looking at your source code, you should see the following in your head

```
<link rel="stylesheet" type="text/css" href="/debugbar/assets/vendor/font-awesome/css/font-awesome.min.css?m=1465818669" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/vendor/highlightjs/styles/github.css?m=1465818669" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/debugbar.css?m=1465818669" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/widgets.css?m=1465818669" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/openhandler.css?m=1465818669" />
<link rel="stylesheet" type="text/css" href="/debugbar/javascript/sqlqueries/widget.css?m=1475596428" />
```

the following at the bottom of your body

`<script type="text/javascript" src="/debugbar/assets/vendor/highlightjs/highlight.pack.js?m=1465818669"></script><script type="text/javascript" src="/debugbar/assets/debugbar.js?m=1465818669"></script><script type="text/javascript" src="/debugbar/assets/widgets.js?m=1465818669"></script><script type="text/javascript" src="/debugbar/assets/openhandler.js?m=1465818669"></script><script type="text/javascript" src="/debugbar/javascript/sqlqueries/widget.js?m=1480675876"></script><script type="text/javascript" src="/debugbar/javascript/widgets.js?m=1473955492"></script>`

and an inline script that triggers initialization with all the data

the html itself looks like the following:

`<div class="phpdebugbar"><div class="phpdebugbar-drag-capture" style="display: none;"></div><div class="phpdebugbar-resize-handle" style="display: block;"></div><div class="phpdebugbar-header" style="display: block;"><div class="phpdebugbar-header-left"><a class="phpdebugbar-tab"><i class="phpdebugbar-fa phpdebugbar-fa-list-alt"></i><span class="phpdebugbar-text">Messages</span>`

**Comment by camexapps** [comment]
Yep, here is is the head code:

I have just copied my results, to see if all set of files are there, compared to yours..

<link rel="stylesheet" type="text/css" href="/debugbar/assets/vendor/font-awesome/css/font-awesome.min.css?m=1482267884" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/vendor/highlightjs/styles/github.css?m=1482267884" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/debugbar.css?m=1482267884" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/widgets.css?m=1482267884" />
<link rel="stylesheet" type="text/css" href="/debugbar/assets/openhandler.css?m=1482267884" />
<link rel="stylesheet" type="text/css" href="/debugbar/javascript/sqlqueries/widget.css?m=1482267884" />

footer code:

<script type="text/javascript" src="/debugbar/assets/vendor/highlightjs/highlight.pack.js?m=1482267884"></script>
<script type="text/javascript" src="/debugbar/assets/debugbar.js?m=1482267884"></script>
<script type="text/javascript" src="/debugbar/assets/widgets.js?m=1482267884"></script>
<script type="text/javascript" src="/debugbar/assets/openhandler.js?m=1482267884"></script>
<script type="text/javascript" src="/debugbar/javascript/sqlqueries/widget.js?m=1482267884"></script>
<script type="text/javascript" src="/debugbar/javascript/widgets.js?m=1482267884"></script>

But no DOM output of the DebugBar itself

**Comment by lekoala** [comment]
do you see any inline javascript that would trigger the debugbar?

at some point you should see after script inclusions. Or maybe you have some security headers that prevent inline script to run?

```
<script type="text/javascript">
var phpdebugbar = new PhpDebugBar.DebugBar();
phpdebugbar.addTab("messages", new PhpDebugBar.DebugBar.Tab({"icon":"list-alt","title":"Messages", "widget": new PhpDebugBar.Widgets.MessagesWidget()}));
phpdebugbar.addIndicator("time", new PhpDebugBar.DebugBar.Indicator({"icon":"clock-o","tooltip":"Request Duration"}), "right");
phpdebugbar.addTab("timeline", new PhpDebugBar.DebugBar.Tab({"icon":"tasks","title":"Timeline", "widget": new PhpDebugBar.Widgets.TimelineWidget()}));
phpdebugbar.addIndicator("memory", new PhpDebugBar.DebugBar.Indicator({"icon":"cogs","tooltip":"Memory Usage"}), "right");
phpdebugbar.addTab("database", new PhpDebugBar.DebugBar.Tab({"icon":"inbox","title":"Database", "widget": new PhpDebugBar.Widgets.SQLQueriesWidget ...
```

**Comment by camexapps** [comment]
Hmm, don’t seem to have the inline JS anywhere..

Couldn’t find any apache logs triggering any security issues either

Appreciate the help, will call it a night now,  and have another look at it in the morning.

Cheers

**Comment by lekoala** [comment]
ok, that's why then

the request filter (DebugBarRequestFilter::postRequest) will include the inline script juste before the closing body </body>

you can check if DebugBar::renderDebugBar returns the script as it should.

if no script is returned (if no renderer is set, in debugbar is not present in the requirements or in ajax context), then you need to check why...

**Comment by camexapps** [comment]
So, still be digging around with no luck, I guess what I find mainly perplexing is that I can get it to work via the admin area fine.

If I do a 

`var_dump(DebugBar::renderDebugBar());`

in the page's init() controller, I do get

 `string '<script type="text/javascript">
var phpdebugbar = new PhpDebugBar.DebugBar();
phpdebugbar.addTab("messages", new PhpDebugBar.DebugBar.Tab({"icon":"list-alt","title":"Messages", "widget": new PhpDebugBar.Widgets.MessagesWidget()}));
phpdebugbar.addIndicator("time", new PhpDebugBar.DebugBar.Indicator({"icon":"clock-o","tooltip":"Request Duration"}), "right");
phpdebugbar.addTab("timeline", new PhpDebugBar.DebugBar.Tab({"icon":"tasks","title":"Timeline", "widget": new PhpDebugBar.Widgets.TimelineWidget()}));
p'... (length=10516)` 

but thats the closest I can get to that script being sent...

If I do something like: ?showqueries=1 I can see the output fine (its not encased in the debug bar area - as thats not showing) at the top of the site template.

![screen shot 2016-12-22 at 15 15 37](https://cloud.githubusercontent.com/assets/1858524/21413046/8deb2822-c859-11e6-9183-197ba97ffa1e.png)

**Comment by lekoala** [comment]
yes showqueries does not depend on the javascript plugin so that's to be expected. 

although the inline script should be automatically appended by the requestfilter, what you could do is simply add in your Page.ss a variable called $RenderDebugBar and add on your Page.php a method that will return the content of DebugBar::renderDebugBar

not perfect because it doesn't explain why the inline script is not added.. the only remaining possibility I see is that in DebugBarRequestFilter::postRequest, the following lines are not working as expected

        // Inject init script into the HTML response
        $body = $response->getBody();
        if (strpos($body, '</body>') !== false) {
            $body = str_replace('</body>', $script.'</body>', $body);
            $response->setBody($body);
        }

do you have a closing body tag? seems silly to ask but maybe it's just a space somewhere like </ body>

**Comment by camexapps** [comment]
Yep, I can confirm adding a $RenderDebugBar method, return the correct Javascript injection code. Checked the </body> tag and looks all good.

I am not sure if this has any relevance, but should the postRequest filter method be firing on a general page view? I ask this because it appears it does not for me, even trying to break the script (e.g using a die() command ), nothing is triggering the postRequest method, which i thought was a bit odd. I was looking into this further, as that is where the renderDebugBar method is supposed to be executed (as you would be are aware)

**Comment by lekoala** [comment]
It is strange indeed. Does the preRequest works? or do you have some part of your controller that triggers die/exit which would prevent the request filter to be applied?

at any rate, I believe it is something specific to your project. You can also try to install a default silverstripe website, add the module and see if it works as expected
