### ISSUE TITLE
SilverStripe 4 compatibility

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#17]
Any plans for SS4 compatibility?

**Comment by lekoala** [comment]
as soon as beta is out :-)

**Comment by lekoala** [comment]
And since the beta is out, I'm going to investigate that very soon :-)

**Comment by robbieaverill** [comment]
If it helps @lekoala our team has some scope to help with/do this upgrade :)

**Comment by lekoala** [comment]
it would be most welcome

**Comment by robbieaverill** [comment]
@lekoala could you create a new branch from `master` called `1` for 1.x support, then merge https://github.com/lekoala/silverstripe-debugbar/pull/45 to kick off SS4 compatibility in master?

We'll also need to update the branch alias in the `1` branch to `"1.x-dev": "1.0.x-dev"` so it's not pointing to `dev-master` any more
