### ISSUE TITLE
Suggest advising adding it as composer dev-requirement

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#2]
Even though disabled, it will still increase the memory footprint of objects and the framework on live sites. Only installing it as require-dev would prevent that from happening.

**Comment by lekoala** [comment]
I made some improvements in 46000e81b55be9bc05912b7d1a0db6164270c4c4 but the best way would be to enable extensions only in dev mode... I tried to do it, but in yml, only the request filter is applied, not the controller extension for some reason... Or maybe I could simply ask the developer to enable the debugbar by himself in mysite/_config.php.

**Comment by Firesphere** [comment]
Adding something like this to your readme.md would be what I mean:

> Either run `composer require lekoala/silverstripe-debugbar --dev`
> 
> Or add `lekoala/silverstripe-debugbar: "dev-master"` to require-dev in your composer.json file

**Comment by lekoala** [comment]
Done 434c0550053a17890ce8912d4eab67080914d698
