### ISSUE TITLE
Deprecate/remove DebugBarDatabaseProxy

### ISSUE THREAD

**Issue by robbieaverill** [lekoala/silverstripe-debugbar#21]
## For feedback

DebugBarDatabaseProxy is SS 3.1 compatible, and DebugBarDatabaseNewProxy is SS 3.2+ compatible. It might be a good idea to set the minimum version requirement for this module to 3.2, deprecate the DebugBarDatabaseProxy class in the 0.x release line and remove it in 1.0.x to reduce duplication and maintenance burden.

I'm sure that there are still plenty of users on 3.1, but it's been EOL for some time now (current minimum supported version is 3.5).

**Comment by lekoala** [comment]
I fully agree ! 3.1 users can use an older version if they want to.
