### ISSUE TITLE
Enable TravisCI, Scrutinizer and Codecov.io

### ISSUE THREAD

**Issue by robbieaverill** [lekoala/silverstripe-debugbar#31]
Hey @lekoala :)

As this module now has Travis configuration which runs Codecov.io code coverage, could you enable TravisCI and ScrutinizerCI? Codecov.io should enable automatically once a successful coverage run on Travis completes.

**Comment by lekoala** [comment]
to be honest, I'm not using Travis or Scrutinizer at the moment so a quick walkthrough on how to do that would be welcome :-)

**Comment by robbieaverill** [comment]
No worries, if you go to their websites and sign in with GitHub it's pretty much plug and play to enable it for your repository :-)

**Comment by lekoala** [comment]
i added travis and scrutinizer. the build is still pending so i'm waiting to see how to configure codecov

**Comment by robbieaverill** [comment]
Nice one. I see there's a failing test, I can PR for that tomorrow. Codecov should enable itself once a successful Travis build with coverage enabled completes - the config for it is in .travis.yml
