### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#4]
Tests are missing. I think adding either Behat or Unit tests would be a good thing to make sure everything stays stable.

**Comment by lekoala** [comment]
For simple integrations like this, I tend to skip tests. However if someone wants to add them, I'll happily merge them.

**Comment by Firesphere** [comment]
To be honest, I don't consider this a "simple integration" ;)

I've learned to test everything. Even the minor things. And it improves your score on the SilverStripe module page!
I tend to agree, but also to disagree :)

**Comment by lekoala** [comment]
:-) tests are always good I know, I'm just terrible at it

**Comment by lekoala** [comment]
a few basic tests are added on master. feel free to let me know if any critical part needs to be tested because it's not always very easy to test extensions/request filters etc
