### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by robbieaverill** [lekoala/silverstripe-debugbar#43]
Hey @lekoala 

With the completed merge of the following PRs, the module seems to be stable enough for a 1.0.0 release - what do you think?

* #37 
* #38 
* #39 
* #40 
* #41 
* #42

The last step would probably be to flesh our the documentation for this module a little more and include some screenshots etc, which I am working on at the moment. I'll push a pull request when it's done.

Our team will be looking at upgrading this for SS4 in the next week or two as well adding a couple of new features which are not really doable in SS3.

Any thoughts on this?

**Comment by lekoala** [comment]
Sounds perfect! I'll have a quick review before releasing 1.0.0 and then we can move on to SS4

**Comment by lekoala** [comment]
Hi @robbieaverill, I added you as a collaborator of this repository so feel free to make any changes that you think necessary :-)

**Comment by robbieaverill** [comment]
Thanks :-)

**Comment by robbieaverill** [comment]
Ok @lekoala I've branched master off to `1` which should be branched off to `1.0` and tagged as 1.0.0 when ready. Master has been updated to 2.0.x-dev compatible, so basically:

* `master` branch: 2.0.x-dev - SS4 compatibility
* `1` branch: 1.x-dev - SS3 compatible

I can do the 1.0.0 release if you'd like me to, just let me know when you're happy with the changes. If you're going to do it, please branch `1` off to `1.0` as well - so basically then `1.0` will become the branch for semver patch fixes on the 1.0.x release line, `1` will become 1.1.x-dev (next minor semver release) and master will be 2.0.x-dev (next major release). When 2.0.0 is beta-ready we can create a 2 branch for it :)

**Comment by lekoala** [comment]
You can go ahead and release 1.0.0 :-) did you have the opportunity to review the changelog to include all the changes that have been made so far?

**Comment by robbieaverill** [comment]
@lekoala OK cool. I'll look at doing this tomorrow some time. Will update the changelog before release. Would you prefer it in the [changelog file](https://github.com/lekoala/silverstripe-debugbar/blob/master/CHANGELOG.md) or on GitHub releases? Are you happy for me to use a more automated approach like [this](https://github.com/silverstripe/silverstripe-userforms/releases/tag/4.3.1) for the changelog format?

**Comment by lekoala** [comment]
Automated GitHub releases sounds much better, so if you can enable them it would be perfect

**Comment by robbieaverill** [comment]
Cool - FYI the bash alias I use to generate them is `alias gcl="git log --oneline --pretty=format:\"* %s (%an) - %h\" --no-merges"`

Use: `gcl 0.1.1..`

You may also consider using something like [github-changelog-generator](https://github.com/skywinder/github-changelog-generator) if you wanted to do it that way, up to you :)

**Comment by robbieaverill** [comment]
All done - thanks for your collaboration @lekoala!

https://github.com/lekoala/silverstripe-debugbar/releases/tag/1.0.0
