### ISSUE TITLE
Consolidate docs?

### ISSUE THREAD

**Issue by chillu** [lekoala/silverstripe-debugbar#59]
@robbieaverill Thanks for writing awesome docs! I do wonder if they're a bit too scattered though - it's quite likely that devs will miss essential docs because they're spread across a dozen pages. Could we condense this into the README? I think in general, anchor links plus a long README are preferrable to mini-pages with half a screen of content. That definitely has it's limits, e.g. the GraphQL module README has grown too large. But in general, there's a lot of power in the ability to skim read by scrolling, and use browser search on a single page.

**Comment by robbieaverill** [comment]
PR at #62

**Comment by robbieaverill** [comment]
Resolved in #62
