### ISSUE TITLE
Icons don't make much sense

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#63]
I feel the currently used icons are not really the best choice. Here's my thought:
- `database` is a more sensible icon for database
- `list` for Parameters?
- `envelope` for Messages
- `cookie` (Not yet available :( ) for cookies (duh)
- `file-code-o` for templates
- `check` for Requirements? (this is a tricky one)

**Comment by sachajudd** [comment]
@Firesphere P.R welcome.

**Comment by lekoala** [comment]
done in master

**Comment by lekoala** [comment]
so i'm closing this to clean up the issues, if you see any other update that can be made, PR would be indeed welcome :-)
