### ISSUE TITLE
Separate core php-debugbar assets from customisations

### ISSUE THREAD

**Issue by robbieaverill** [lekoala/silverstripe-debugbar#65]
To make way for pre-processed assets (e.g. #53).

Currently the `assets/debugbar.css` for example has some customisations. We should use a location that is obvious that it's a third party file that shouldn't be touched.

## Acceptance criteria

* Latest version of php-debugbar's assets are copied through to `assets/vendor/php-debugbar`
* Customisations to `assets/debugbar.css` as well as the other CSS and Javascript files in that folder are moved to a new folder (e.g. `css/`)
* Documentation makes it easy for devs to find out which files to change when contributing

**Comment by lekoala** [comment]
I've made some progress on this with https://github.com/lekoala/silverstripe-debugbar/commit/b0831765a71765045f7eb3f81f28ddf846f34987 but i'm not sure how to proceed for js files

**Comment by lekoala** [comment]
ok i'll just close this, i think we are never going to separate more than it currently is. debugbar is just not flexible enough and since then, nothing has changed and it will probably never will
at this stage i think it's safer just to have our own compatible js
