### ISSUE TITLE
Add ability to disable tabs with configuration

### ISSUE THREAD

**Issue by robbieaverill** [lekoala/silverstripe-debugbar#66]
As a developer,
I want to be able to disable certain tabs (e.g. Templates or SiteConfig),
Because I may not like or want them for my dev environments

**Comment by lekoala** [comment]
I added the ability to disable the config, partial cache and email collector. We could further modularize how the SilverStripe collector works to allow more specific settings.

**Comment by lekoala** [comment]
closing old issue
