### ISSUE TITLE
enabled_in_admin setting fails when site in subfolder

### ISSUE THREAD

**Issue by MattyBalaam** [lekoala/silverstripe-debugbar#68]
isAdminUrl check returns false negative if debugbar is used in a subfolder

e.g. url is  localhost://mydevelopent/admin

**Comment by lekoala** [comment]
maybe it makes more check to check for admin controller anyway ?

it would be more bulletproof. also it needs to take into account that the admin path can be changed.

**Comment by robbieaverill** [comment]
We can't check for the current controller in SS4 because the middleware is executed before the controller context is active

**Comment by lekoala** [comment]
ah yes now I remember why I wasn't doing that :-)

then we should remove the base url from the request url to make the check accurate that should be fairly easy
