### ISSUE TITLE
Capture and incorporate ?debug and ?debug_request

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#8]
It would be nice if the Request-tab would include the output from ?debug and ?debug_request url variables.
I understand that this is not very easy to incorporate, but I think it would add a lot of value.

**Comment by lekoala** [comment]
yes, I looked into that, but this require core changes basically because the Debug class that is use for this simply echoes the content and is not injectable. Do you think of any other way to handle this?

**Comment by Firesphere** [comment]
I don't have an answer straight away, but I think it can be done with an `Extension`.
I think it would require a partial rewrite of the core indeed. I've done it a few times to show db-queries in FirePHP for example, but that's some serious hacking ;) (Also, it'll probably crash your browser).
I haven't really looked at how to do this, but if I find something, I'll definitely get back on this!

**Comment by lekoala** [comment]
well, I played with an idea with the current master, I buffered all output before the call to the action. This way any "debug" output is caught and passed to a new tab.
You can try on the current master and tell me what you think.

**Comment by lekoala** [comment]
I'm closing this, since I think I did most of what's possible given the current state of SilverStripe
