### ISSUE TITLE
adding disable flag in _ss_environment.php does not remove it

### ISSUE THREAD

**Issue by asecondwill** [lekoala/silverstripe-debugbar#82]
If i put this in _ss_environment.php i still get the debug bar. 

````  putenv('DEBUGBAR_DISABLE=true'); ````

 If i want to remove / add this per environment (not based on dev/live) how should I do that?

**Comment by lekoala** [comment]
you need to define a constant. define('DEBUGBAR_DISABLE',true). but it could be nice to read the environment to do so

**Comment by robbieaverill** [comment]
Environment variable support is default in the SS4 compatible version of debugbar. You could PR this into the SS3 version if you'd like to @asecondwill?

**Comment by asecondwill** [comment]
happy to wait for 4.  not long now.
