### ISSUE TITLE
Truncate long PHP version number

### ISSUE THREAD

**Issue by chillu** [lekoala/silverstripe-debugbar#85]
![image](https://user-images.githubusercontent.com/111025/31306316-060db544-ab45-11e7-8dab-81a6d86950c3.png)

**Comment by robbieaverill** [comment]
I have a feeling this comes from the underlying php-debugbar library, but with investigating

**Comment by lekoala** [comment]
this seems due to the usage of PHP_VERSION constant in the default PhpInfoCollector

> PHP_VERSION (string)
> The current PHP version as a string in "major.minor.release[extra]" notation.

either we fix it on our side, our we make a pull request to use something without any [extra] data

**Comment by robbieaverill** [comment]
PR at https://github.com/lekoala/silverstripe-debugbar/pull/114. I'll raise an issue upstream - I thought about adding this directly to their collector, but it might be opinionated to do so (for the wider community). Will see what happens with an issue on their end.

**Comment by robbieaverill** [comment]
Upstream issue: https://github.com/maximebf/php-debugbar/issues/413

**Comment by robbieaverill** [comment]
This is fixed in https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.0.3
