### ISSUE TITLE
Should it work with ss3.6.2 on php7.1?

### ISSUE THREAD

**Issue by brasileric** [lekoala/silverstripe-debugbar#87]
Hi,
Can't get it working on ss3.6.2 on php7.1, not in frontend and not in admin. Environment is dev (setting in _ss_environment.php).
Should it work with this combination?

**Comment by lekoala** [comment]
it should! do you get something by calling DebugBar::getDebugBar() in your controller? you can also call "whyDisabled"

**Comment by brasileric** [comment]
Okay, good to know than I'm gonna figure it out further.

**Comment by brasileric** [comment]
hi Lekoala. Today I had time to try again. It was because I use vagrant, so not local ip. Disabled that check and works great now. One of the most useful SilverStripe modules! :)

Thanks for your suggestion.
