### ISSUE TITLE
Replace getenv calls with SilverStripe\Core\Environment::getEnv()

### ISSUE THREAD

**Issue by robbieaverill** [lekoala/silverstripe-debugbar#88]
Use of `getenv` is now not suggested, but instead we should use `SilverStripe\Core\Environment::getEnv()` to ensure thread safe compatibility.

**Comment by lekoala** [comment]
done (also, it is required otherwise setting the flag in .env does not work)

ps : yay i finally managed to test this module on ss4

**Comment by robbieaverill** [comment]
Nice, thanks @lekoala! There's a PR to fix the Travis builds at #89 

Fixed with b9e4d0e
