### ISSUE TITLE
Show only duplicate queries

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#9]
Although it highlights which queries are apparently duplicates, it would be nice to filter them by "duplicate only" and grouped by statement, to see where there could be some optimisations.

**Comment by lekoala** [comment]
I agree, it would also be nice to log slow queries and such. Currently I'm using the default widget which does not have this option, but it may be worth investigating how to create a custom widget that would do that

**Comment by lekoala** [comment]
Hi there,

I've made a couple of changes to the sqlqueries widget, not so difficult after all. You have a now a filter for duplicated queries and a badge to indicate which queries are the same.

You can also filter by database (if you use more than one).

And finally, to help you, query source has been added to easily identify what triggers the query

Have fun :-)

**Comment by Firesphere** [comment]
Awesome! But... I have thought of a new issue... ;)
