### ISSUE TITLE
composer require error

### ISSUE THREAD

**Issue by cansozeri** [lekoala/silverstripe-debugbar#92]
Hi if you use as suggested install method - it throws error like this because it is gonna try to add 1.1-dev

```
composer require --dev lekoala/silverstripe-debugbar

lekoala/silverstripe-debugbar 1.1.x-dev requires silverstripe/framework ~3.2 

```
My silverstripe is 4.0.0 - So I just used.

`"lekoala/silverstripe-debugbar":"dev-master"`

**Comment by robbieaverill** [comment]
Hi @cansozeri, the SS4 version is not yet tagged as stable, so please install the 2.x version instead (any of these options):

```
composer require --dev lekoala/silverstripe-debugbar ^2@dev
composer require --dev lekoala/silverstripe-debugbar 2.0.x-dev
```
