### ISSUE TITLE
Silverstripe 4.1

### ISSUE THREAD

**Issue by andreaslindahl** [lekoala/silverstripe-debugbar#96]
Doesn't this work with Silverstripe 4.1? I'm getting errors when running the site after installing this:

```
[Emergency] Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class Psr\SimpleCache\CacheInterface.cacheblock does not exist in /Library/WebServer/Documents/rtv_ss4/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php:17 Stack trace: #0 

Trace
SilverStripe\Core\Injector\InjectionCreator->create(Psr\SimpleCache\CacheInterface.cacheblock, Array) 
Injector.php:585
SilverStripe\Core\Injector\Injector->instantiate(Array, Psr\SimpleCache\CacheInterface.cacheblock, singleton) 
Injector.php:988
SilverStripe\Core\Injector\Injector->getNamedService(Psr\SimpleCache\CacheInterface.cacheblock, 1, Array) 
Injector.php:941
SilverStripe\Core\Injector\Injector->get(Psr\SimpleCache\CacheInterface.cacheblock) 
SSViewer.php:558
SilverStripe\View\SSViewer->getPartialCacheStore() 
SSViewer.php:596
SilverStripe\View\SSViewer->includeGeneratedTemplate(/Library/WebServer/Documents/rtv_ss4/silverstripe-cache/_www/.cachevendor.silverstripe.assets.templates.SilverStripe.Assets.Flysystem.PublicAssetAdapter_HTAccess.ss, SilverStripe\View\ArrayData, , Array, ) 
SSViewer.php:674
SilverStripe\View\SSViewer->process(SilverStripe\View\ArrayData, , ) 
SSViewerProxy.php:36
LeKoala\DebugBar\Proxy\SSViewerProxy->process(SilverStripe\View\ArrayData) 
AssetAdapter.php:191
SilverStripe\Assets\Flysystem\AssetAdapter->renderTemplate(SilverStripe\Assets\Flysystem\PublicAssetAdapter_HTAccess) 
AssetAdapter.php:154
SilverStripe\Assets\Flysystem\AssetAdapter->configureServer(1) 
AssetAdapter.php:120
SilverStripe\Assets\Flysystem\AssetAdapter->flush() 
FlysystemAssetStore.php:897
SilverStripe\Assets\Flysystem\FlysystemAssetStore::flush() 
FlushMiddleware.php:22
SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
RequestProcessor.php:66
SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
SessionMiddleware.php:20
SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
AllowedHostsMiddleware.php:60
SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
TrustedProxyMiddleware.php:176
SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) 
Director.php:370
SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:48
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure, SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:66
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure, SilverStripe\Control\HTTPRequest) 
ErrorControlChainMiddleware.php:56
SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain) 
call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain) 
ErrorControlChain.php:236
SilverStripe\Core\Startup\ErrorControlChain->step() 
ErrorControlChain.php:226
SilverStripe\Core\Startup\ErrorControlChain->execute() 
ErrorControlChainMiddleware.php:69
SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) 
HTTPApplication.php:67
SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1) 
HTTPApplication.php:49
SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) 
index.php:26

```

**Comment by robbieaverill** [comment]
Have you flushed?

**Comment by andreaslindahl** [comment]
Yes. I'm actually getting the error when flushing...

**Comment by xillonz** [comment]
I can't even install it with composer:

"lekoala/silverstripe-debugbar 1.1.0 requires silverstripe/framework ~3.2"

**Comment by andreaslindahl** [comment]
1.1.0 requires 3.2, yes. Use dev-master instead.

**Comment by xillonz** [comment]
Sorry, I just wrote the command in the docs. How do I specify the version?

**Comment by andreaslindahl** [comment]
Writing "composer require lekoala/silverstripe-debugbar dev-master" in your console should work

**Comment by robbieaverill** [comment]
We should not be suggesting to use dev-master in the docs. You should use the branch alias for it instead, e.g. `2.x-dev` - pull requests to update the readme are welcome :)

**Comment by lekoala** [comment]
also v2 is pretty much ready to release, any pending issues that prevent a release?

**Comment by robbieaverill** [comment]
This issue should probably be resolved first (or at least validated) but otherwise I don't think so :)

**Comment by lekoala** [comment]
since the proxy is not doing much, I don't see how the issue could be related to this module. If the cache service is not available for some reasons, it should be handled by SSViewer instead no?

of course, we could add a try/catch block around the parent:process call and return something instead, but I don't see how that would help

**Comment by andreaslindahl** [comment]
All I know is that I get this error when using this module. Of course, it's entirely possible that the source of the error lies elsewhere.

**Comment by lekoala** [comment]
perhaps it has to do with how the injector is configured in debugbar.yml but it's really difficult to tell. I see a couple of "cacheblock" reference there as well

i've moved the cache configuration to it's own yml file to ensure it's loaded after corecache. maybe it's simply that.

can you try ?

**Comment by trevorpan** [comment]
I've installed SS4.1.1. This is the main composer.json file in tpan/public/composer.json

The project files folders have been updated to meet the SS Lesson #1.

    {
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.1@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "maximebf/debugbar": "1.*",
        "jdorn/sql-formatter": "dev-master"
          }
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7"
    },
    "extra": {
        "branch-alias": {
            "4.x-dev": "4.2.x-dev",
            "dev-master": "5.x-dev"
        },
        "project-files-installed": [
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
    }

I don't know why I get this error. 

I've required the jdorn/sqlformatter and "maximebf/debugbar": "1.*". But terminal says it won't accept PHP 7+. When I look at the composer requirements it's anything above >=5.6.0. This composer file is what shipped with the SS4.1.1 base project.

    Trevors-Mac-mini:trevorpan trevorpan$ composer require --dev lekoala/silverstripe-debugbar

    Warning: Module 'intl' already loaded in Unknown on line 0
    Plugin command require-recipe (SilverStripe\RecipePlugin\RequireRecipeCommand) would     override a Composer command and has been skipped
    Plugin command update-recipe (SilverStripe\RecipePlugin\UpdateRecipeCommand) would override a Composer command and has been skipped
    Using version ^1.1 for lekoala/silverstripe-debugbar
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - silverstripe/framework 3.5.x-dev requires php >=5.3.3,<7 -> your PHP version (7.1.12) does    not satisfy that requirement.
        - Conclusion: remove silverstripe/framework 4.0.3
       - Conclusion: don't install silverstripe/framework 4.0.3
        - lekoala/silverstripe-debugbar 1.x-dev requires silverstripe/framework ~3.2 -> satisfiable by   silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.7.x-dev, 3.x-dev].
        - lekoala/silverstripe-debugbar 1.1.x-dev requires silverstripe/framework ~3.2 -> satisfiable by  silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.7.x-dev, 3.x-dev].
        - lekoala/silverstripe-debugbar 1.1.0 requires silverstripe/framework ~3.2 -> satisfiable by  silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.7.x-dev, 3.x-dev].
        - Can only install one of: silverstripe/framework[3.6.x-dev, 4.0.3].
        - Can only install one of: silverstripe/framework[3.7.x-dev, 4.0.3].
        - Can only install one of: silverstripe/framework[3.x-dev, 4.0.3].
        - Installation request for silverstripe/framework (locked at 4.0.3, required as ~4.0.0) -> satisfiable by silverstripe/framework[4.0.3].
        - Installation request for lekoala/silverstripe-debugbar ^1.1 -> satisfiable by lekoala/silverstripe-  debugbar[1.1.0, 1.1.x-dev, 1.x-dev].


    Installation failed, reverting ./composer.json to its original content.
    Trevors-Mac-mini:trevorpan trevorpan$

**Comment by robbieaverill** [comment]
Hi @trevorpan 

You need to use debugbar ^2 for SilverStripe 4. It's trying to install ^1 because we haven't released a stable 2 tag for it yet, and you didn't specify a version to install

Try `composer require --dev lekoala/silverstripe-debugbar ^2.0`

**Comment by lekoala** [comment]
hey @robbieaverill should we release a stable version? current status might not be perfect, but it is stable enough to be used on a dev environment anyway.

**Comment by robbieaverill** [comment]
Yep, totally! Let's do it. We can then iterate as required :)

**Comment by lekoala** [comment]
I'll let you do it if that's ok you seem to have a fine release process :-)

**Comment by robbieaverill** [comment]
Cool, done https://github.com/lekoala/silverstripe-debugbar/releases/tag/2.0.0

I've created a 2.0 branch too for semver patch changes against the 2.0.x line. Any new enhancements or breaking changes should go into the master branch for the 2.1.x release at some point.

**Comment by trevorpan** [comment]
Great @robbieaverill @lekoala ! Thank you. Made it past the install. 

This is what I received: 
    Trevors-Mac-mini:trevorpan trevorpan$ composer require --dev lekoala/silverstripe-debugbar ^2.0

Warning: Module 'intl' already loaded in Unknown on line 0
Plugin command require-recipe (SilverStripe\RecipePlugin\RequireRecipeCommand) would override a Composer command and has been skipped
Plugin command update-recipe (SilverStripe\RecipePlugin\UpdateRecipeCommand) would override a Composer command and has been skipped
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing tractorcow/classproxy (0.1.2): Downloading (100%)         
  - Installing tractorcow/silverstripe-proxy-db (0.1.0): Downloading (100%)         
  - Installing jdorn/sql-formatter (dev-master 7ef9b85): Cloning 7ef9b85961 from cache
  - Installing lekoala/silverstripe-debugbar (2.0.0): Downloading (100%)         
Exposing web directories for silverstripe-vendormodule lekoala/silverstripe-debugbar with method auto:
  - assets
  - javascript
Package tractorcow/recipe-plugin is abandoned, you should avoid using it. Use silverstripe/recipe-plugin instead.
Writing lock file
Generating autoload files

Should the bar pop-up automatically? I've added the debugbar.yml to app/_config/ but do not see the bar? Using Firefox Developer Edition.
    ---
    Name: mysitedebugbar
    ---
    LeKoala\DebugBar\DebugBar:
      enabled_in_admin: false
      query_limit: 500

**Comment by robbieaverill** [comment]
@trevorpan you can check why it may not be running by looking at `DebugBar::whyDisabled()`.

If you're running inside a vagrant VM, that's a common reason.

**Comment by robbieaverill** [comment]
I'm going to close this issue for now, since I've been using this regularly on 4.0/4.1/4.2/4.3 projects without problems. Feel free to reopen if you'd like to though!
