### ISSUE TITLE
How to show this bar?

### ISSUE THREAD

**Issue by zzdjk6** [lekoala/silverstripe-debugbar#99]
I am confused about the usage of this module. After install it via composer, it didn't show up automatically, even when request with "debug" and "debug_request".

Is there any step I need go through to make this module work? Maybe I need to change some configurations?

**Comment by zzdjk6** [comment]
I am using SS 4.1.1 and debugbar 2.0.0-beta1

**Comment by robbieaverill** [comment]
Do you have your SS_ENVIRONMENT_TYPE set to dev?

**Comment by zzdjk6** [comment]
Yes, I have set the SS_ENVIRONMENT_TYPE to dev in ".env" file

**Comment by robbieaverill** [comment]
Did you flush?

**Comment by zzdjk6** [comment]
Yes, I executed `flush`, and even 'dev/build', but they didn't make any difference.

So it seems that this module should work after installation with only a .env setting and flush? 

Then I guess some of my configurations or customizations in the project prevent this module working correctly.  I will use a clean installation of SilverStripe with a demo application to do a test.

**Comment by lekoala** [comment]
a few things that can help:
- call DebugBar::whyDisabled to see if it returns anything?
- check if there is any js error and check html source to see if anything is actually injected

**Comment by lemon-pie-now** [comment]
Following as I haven't been able to display the bar after install and dev mode se and php debugbar installed  SS4.

WhyDissabled shows: "I don't know why"

flushing after adding a call to whyDisabled returns: Fatal error: Uncaught exception 'BadMethodCallException' with message 'Infinite loop detected. Config could not be bootstrapped.' in ..\site\vendor\silverstripe\config\src\Collections\CachedConfigCollection.php:133 Stack trace: #0

**Comment by zzdjk6** [comment]
Sorry for the late update, I found my issue. My debug bar was not displayed because I was using `Docker`, so that I need to set `check_local_ip` to `false`.
